name: Deploy to Production

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'

jobs:
  deploy-metadata:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Target Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > ./auth_url.txt
          sf org login auth sfdx-url --sfdx-url-file ./auth_url.txt --set-default
          rm ./auth_url.txt -a Project1

      # Executes the live deployment to the target environment
      - name: Deploy Metadata
        run: |
          sf project deploy start --source-dir force-app -u Project1 --wait 30
